# Компилятор
CXX = g++

# Флаги компиляции
CXXFLAGS = -IInclude -Isrc/include -Wall -Wextra -std=c++11

# Папка с объектными файлами
OBJ_DIR = obj

# Исходные файлы
SRCS = main.cpp \
       CPP/Circle.cpp \
       CPP/Rectangle.cpp \
       CPP/Square.cpp \
       CPP/Triangle.cpp \
       CPP/Figure.cpp

# Объектные файлы
OBJS = $(patsubst %.cpp, $(OBJ_DIR)/%.o, $(SRCS))

# Исполняемый файл
TARGET = SDL2

# Библиотеки SDL2
SDL_LIBS = -Lsrc/lib -lSDL2

# Правило по умолчанию
all: $(TARGET)

# Правило сборки исполняемого файла
$(TARGET): $(OBJS)
	$(CXX) -o $@ $^ $(SDL_LIBS)

# Правило для сборки объектных файлов
$(OBJ_DIR)/%.o: %.cpp
	@if not exist $(OBJ_DIR) mkdir $(OBJ_DIR)
	@if not exist $(OBJ_DIR)/CPP mkdir $(OBJ_DIR)/CPP
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Очистка
clean:
	del /Q $(OBJ_DIR)\*.o
	rmdir /S /Q $(OBJ_DIR)
	del /Q $(TARGET)

.PHONY: all clean
